
let collection;let state=loadState();const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));document.addEventListener("DOMContentLoaded",init);
async function init(){collection=await (await fetch("./data/collection.json?v=5")).json();document.title=collection.appName;wireTabs();wireDataActions();renderAll();if("serviceWorker" in navigator){navigator.serviceWorker.register("./service-worker.js?v=5").catch(()=>{})}}
function stickerIds(){return[...collection.teams.flatMap(t=>Array.from({length:20},(_,i)=>`${t.code}-${i+1}`)),...collection.specials.flatMap(s=>s.items.map(n=>`${s.code}-${n}`))]}
function statsFor(ids){let owned=0,repeated=0;ids.forEach(id=>{const v=getStickerState(state,id);if(v>=1)owned++;if(v>=2)repeated+=(v-1)});return{owned,repeated,missing:ids.length-owned,total:ids.length}}
function teamIds(t){return Array.from({length:20},(_,i)=>`${t.code}-${i+1}`)}function specialIds(s){return s.items.map(n=>`${s.code}-${n}`)}
function stickerNameFor(id){const [code,num]=id.split("-");const team=collection.teams.find(t=>t.code===code);if(team){return team.stickers?.[num]||`${team.code} ${num}`;}const special=collection.specials.find(s=>s.code===code);if(special){return special.labels?.[num]||`${special.code} ${num}`;}return id}
function stickerSubtitleFor(id){const [code,num]=id.split("-");const team=collection.teams.find(t=>t.code===code);if(team)return `${team.name} · ${code} ${num}`;const sp=collection.specials.find(s=>s.code===code);if(sp){const teamName=sp.teams?.[num];return `${sp.name}${teamName?` · ${teamName}`:""}`;}return ""}
function flagMarkup(t){
  if(t.flagType === "css"){
    return `<span class="flag-css ${t.flag}" aria-label="${t.name} flag"></span>`;
  }
  if(t.flag==="custom-sco")return '<span class="flag-badge flag-sco" aria-label="Scotland"></span>';
  if(t.flag==="custom-eng")return '<span class="flag-badge flag-eng" aria-label="England"></span>';
  return `<span class="emoji-flag">${t.flag}</span>`;
}
function normalizeText(s){return (s||"").toString().normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function renderAll(){renderDashboard();renderTeams();renderSpecials();renderSwaps()}

function renderFlag(team){
  if(team.flagType === "css"){
    return `<span class="flag-css ${team.flag}" aria-label="${team.name} flag"></span>`;
  }
  return team.flag || "";
}

function renderDashboard(){const all=statsFor(stickerIds()),pct=all.total?Math.round(all.owned/all.total*100):0;$("#progressRing").style.setProperty("--progress",`${pct*3.6}deg`);$("#percentText").textContent=pct+"%";$("#ownedTotal").textContent=`${all.owned} / ${all.total}`;$("#missingTotal").textContent=all.missing;$("#repeatedTotal").textContent=all.repeated;$("#completeTeams").textContent=`${collection.teams.filter(t=>statsFor(teamIds(t)).owned===20).length}/48`;const teamAll=statsFor(collection.teams.flatMap(teamIds));$("#teamProgress").textContent=Math.round(teamAll.owned/teamAll.total*100)+"%";$("#fwcProgress").textContent=`${statsFor(specialIds(collection.specials[0])).owned}/20`;$("#ccProgress").textContent=`${statsFor(specialIds(collection.specials[1])).owned}/12`;$("#groupOverview").innerHTML=[...new Set(collection.teams.map(t=>t.group))].map(g=>{const teams=collection.teams.filter(t=>t.group===g),gs=statsFor(teams.flatMap(teamIds)),pct=Math.round(gs.owned/gs.total*100),color=teams[0].color;return `<article class="group-card"><div class="group-head" style="background:${color}; color:#071f1b"><span>Grupo ${g}</span><span>${gs.owned}/${gs.total} · ${pct}%</span></div><div class="group-teams">${teams.map(t=>{const s=statsFor(teamIds(t));return `<div class="mini-team"><span>${flagMarkup(t)} ${t.code}</span><b>${s.owned}/20</b></div>`}).join("")}</div></article>`}).join("")}
function renderTeams(){const q=normalizeText($("#searchInput")?.value||"");let html="";let directResults="";if(q){const ids=stickerIds().filter(id=>normalizeText(`${formatId(id)} ${stickerNameFor(id)} ${stickerSubtitleFor(id)}`).includes(q));if(ids.length){directResults=`<article class="group-card"><div class="group-head" style="background:#c9e33a; color:#071f1b"><span>Resultados de búsqueda</span><span>${ids.length}</span></div><div class="search-results">${ids.slice(0,80).map(id=>stickerButton(id,formatId(id),stickerNameFor(id),stickerSubtitleFor(id))).join("")}</div></article>`}}
[...new Set(collection.teams.map(t=>t.group))].forEach(g=>{const teams=collection.teams.filter(t=>t.group===g).filter(t=>!q||normalizeText(`${t.code} ${t.name} grupo ${t.group}`).includes(q));if(!teams.length)return;html+=`<article class="group-card"><div class="group-head" style="background:${teams[0].color}; color:#071f1b"><span>Grupo ${g}</span><span>${teams.length} equipos</span></div>`;teams.forEach(t=>{const s=statsFor(teamIds(t));html+=`<div class="team-row" data-team="${t.code}"><div class="flag">${flagMarkup(t)}</div><div class="team-name"><strong>${t.name}</strong><span>${t.code} · Grupo ${t.group}</span><div class="progress-line"><i style="width:${s.owned/20*100}%"></i></div></div><div class="count">${s.owned}/20</div></div>`});html+=`</article>`});$("#teamsList").innerHTML=directResults+html||`<p class="hint">No hay resultados.</p>`;$(".team-row")&&$$(".team-row").forEach(r=>r.addEventListener("click",()=>openTeam(r.dataset.team)));wireStickerButtons();$("#searchInput").oninput=renderTeams}
function renderSpecials(){$("#specialsList").innerHTML=collection.specials.map(s=>{const st=statsFor(specialIds(s));return `<article class="special-card"><div class="special-head"><div><span class="special-icon">${s.icon}</span> <strong>${s.name}</strong></div><b>${st.owned}/${st.total}</b></div><div class="progress-line"><i style="width:${st.owned/st.total*100}%"></i></div><div class="sticker-grid">${s.items.map(n=>stickerButton(`${s.code}-${n}`,`${s.code} ${n}`,s.labels?.[n],s.teams?.[n]||"Especial")).join("")}</div></article>`}).join("");wireStickerButtons()}
function renderSwaps(){const ids=stickerIds(),missing=ids.filter(id=>getStickerState(state,id)===0),repeated=ids.filter(id=>getStickerState(state,id)>=2);$("#missingList").innerHTML=missing.map(id=>`<span class="pill missing" title="${stickerNameFor(id)}">${formatId(id)}</span>`).join("")||`<p class="hint">No te falta ninguno.</p>`;$("#repeatedList").innerHTML=repeated.map(id=>`<span class="pill repe" title="${stickerNameFor(id)}">${formatId(id)} x${getStickerState(state,id)-1}</span>`).join("")||`<p class="hint">No tienes repetidos.</p>`}
function openTeam(code){const t=collection.teams.find(x=>x.code===code),s=statsFor(teamIds(t));$("#modalContent").innerHTML=`<h2>${flagMarkup(t)} ${t.name}</h2><p class="hint">${t.code} · Grupo ${t.group} · ${s.owned}/20 cromos</p><div class="sticker-grid">${Array.from({length:20},(_,i)=>{const n=String(i+1);return stickerButton(`${t.code}-${n}`,`${t.code} ${n}`,t.stickers?.[n]||"",t.name)}).join("")}</div>`;$("#teamModal").setAttribute("aria-hidden","false");wireStickerButtons()}
function stickerButton(id,label,name="",subtitle=""){const v=getStickerState(state,id),cls=v===0?"nole":v===1?"lete":"repe";return `<button class="sticker ${cls}" data-sticker="${id}"><strong>${label}</strong>${name?`<em>${name}</em>`:""}${subtitle?`<small>${subtitle}</small>`:""}<span>${stateLabel(v)}</span></button>`}
function wireStickerButtons(){$$(".sticker").forEach(btn=>{let timer;btn.addEventListener("click",()=>{const id=btn.dataset.sticker;state[id]=nextStickerState(getStickerState(state,id));saveState(state);renderAll();if($("#teamModal").getAttribute("aria-hidden")==="false"){const code=id.split("-")[0];if(collection.teams.some(t=>t.code===code))openTeam(code)}});btn.addEventListener("contextmenu",e=>e.preventDefault());btn.addEventListener("pointerdown",()=>{timer=setTimeout(()=>{state[btn.dataset.sticker]=0;saveState(state);renderAll();const code=btn.dataset.sticker.split("-")[0];if(collection.teams.some(t=>t.code===code))openTeam(code)},650)});["pointerup","pointerleave","pointercancel"].forEach(evt=>btn.addEventListener(evt,()=>clearTimeout(timer)))})}
function wireTabs(){$$(".tab").forEach(tab=>tab.addEventListener("click",()=>{$$(".tab").forEach(t=>t.classList.remove("active"));$$(".view").forEach(v=>v.classList.remove("active"));tab.classList.add("active");$("#"+tab.dataset.view).classList.add("active")}));$("#closeModal").addEventListener("click",closeModal);$("#teamModal").addEventListener("click",e=>{if(e.target.id==="teamModal")closeModal()})}function closeModal(){$("#teamModal").setAttribute("aria-hidden","true")}
function wireDataActions(){$("#exportBtn").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="panini-world-cup-2026-backup.json";a.click();URL.revokeObjectURL(a.href)});$("#importInput").addEventListener("change",async e=>{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());state=data.state||data||{};saveState(state);renderAll();alert("Backup importado.")});$("#resetBtn").addEventListener("click",()=>{if(confirm("¿Seguro que quieres reiniciar toda la colección?")){state={};saveState(state);renderAll()}})}function formatId(id){return id.replace("-"," ")}
